### ISSUE TITLE
Top-level diagram of system architecture

### ISSUE THREAD

**Issue by harrisj** [harrisj/confidential-survey#14]

**Comment by harrisj** [comment]
![confidential survey system architecture diagram](https://cloud.githubusercontent.com/assets/2044/12803577/729e6ca8-cab9-11e5-83f6-c1bd7805518d.png)

How is this?

**Comment by harrisj** [comment]
@NoahKunin @DavidEBest is this good enough for a system diagram? (Data flow diagrams will be in #18)

**Comment by DavidEBest** [comment]
@harrisj I'd follow Noah's advice (CF Router & Marketplace services) and Alan's example with the last version of the micropurchase diagram here: https://github.com/18F/micropurchase/issues/94

**Comment by harrisj** [comment]
Argh. This is what I get for not scrolling. Will do

Sent from my iPhone

On Feb 4, 2016, at 8:59 AM, David Best notifications@github.com wrote:

@harrisj https://github.com/harrisj I'd follow Noah's advice (CF Router &
Marketplace services) and Alan's example with the last version of the
micropurchase diagram here: 18F/micropurchase#94
https://github.com/18F/micropurchase/issues/94

**Comment by harrisj** [comment]
Revised diagram is in the ATO folder and here

![confidential survey system architecture diagram 1](https://cloud.githubusercontent.com/assets/2044/12820821/b49ef198-cb2e-11e5-97eb-1b84b2b4f8d8.png)

**Comment by DavidEBest** [comment]
This looks pretty good. I don't have anything to add.

**Comment by harrisj** [comment]
This is now included within https://github.com/18F/cg-compliance/pull/33
